# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f222785055c35d593dab746057662b92f8d96c4b916efd58201e1910916591a9c6dc8fb4fa2c6a056e95636439480f87ca9339dd1e834a76114e7334e17c078d

test:
  secret_key_base: ac2948bb630e35a7a3c53f3cf4be0c23f508fd96cd2e1a1d4f741c1fb4718a2999d8fd395cec39932e64e2ddb60936d39d00436862b7ba9222232749e5a65bd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
